#!/bin/bash

case $1 in
    flash )
        umtrx_net_burner --addr=192.168.10.2 --fpga=/usr/share/umtrx/firmware/u2plus_umtrx_v2.bin --fw=/usr/share/umtrx/firmware/umtrx_txrx_uhd.bin --reset
        ;;
    check )
        ;;
    * )
        cat <<-EOF
        Usage:
        $0 flash  - burn packaged firmware to umtrx
        $0 check  - compare versions of packaged firmware and one installed on umtrx
EOF
        ;;
esac
